[project]
name = "mazegen"
version = "1.0.0"
description = "Maze generation library"
readme = "mazegen/README.md"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools]
packages = ["mazegen"]

[tool.setuptools.package-data]
mazegen = ["README.md"]
